### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by fouad-semaan** [souravrs999/Noise.cash-Bot#1]
I set up the bot but I am having this error:

Traceback (most recent call last):
  File "C:\Users\fouad\Github\noisecash\Noise.cash-Bot\NoiseCash.py", line 230, in <module>
    Bot = NoiseCash()
TypeError: __init__() missing 1 required positional argument: 'browser'

How to solve it please?

**Comment by souravrs999** [comment]
This won't work mate its a super old version

**Comment by fouad-semaan** [comment]
Is there a new version? Or any bot to use for some passive income? I really need something bro, please.

**Comment by souravrs999** [comment]
Yes I do have a newer version that is hosted on heroku that constantly post stupid shit it currently makes around 1$ per day, but its not yet uploaded to gihub

**Comment by fouad-semaan** [comment]
Can I get it from heroku? Can u send me please your repo link or id?

**Comment by souravrs999** [comment]
You can't get the source code form a heroku dyno but heres the link hope you have some luck

https://noise-cash-bak.herokuapp.com/

**Comment by fouad-semaan** [comment]
hehe yes it is not easy since my first time on heroku and I don't want to disturb you to guide me with some steps to do
